require "valanga/version"
require "valanga/error"
require "valanga/client"
require "valanga/music"
require "valanga/music_attribute"
require "valanga/music_attribute/base"
require "valanga/music_attribute/groovin"
require "valanga/music_attribute/collete"
